### PR TITLE
No macro expansion by default

### LINKED ISSUE #8: Remove Markdown dependency
the list of macro seems a bit arbitrary for users:

https://github.com/JuliaPluto/ExpressionExplorer.jl/blob/5766ad187fc2d812d21e0fdac4604eebacf2a77c/src/explore.jl#L1034-L1040

Maybe provide a way for configurations to provide with defaults:

```julia
ExpressionExplore.can_macroexpand(::AbstractExpressionExplorerConfiguration, e::Union{Expr,Symbol}) = false
ExpressionExplore.macroexpand_module(::AbstractExpressionExplorerConfiguration) = MacroExpandInHere
```

### PR DESCRIPTION
**Pull request by fonsp**
I think this might be nicer, but we should document how to macroexpand before using EE.

Maybe we should also provide a help function that macroexpands macros that are known, but not the rest? Like

```julia
# ╔═╡ b6c56df1-a693-434a-98d7-2bb8fe185343
function trymacroexpand(e::Expr; mod::Module)
	if e.head === :macrocall
		try
			e = macroexpand(mod, e; recursive=false)
		catch ex
			@warn "failed ro expand" ex=(ex,catch_backtrace()) e.args[1]
		end
	end
	Expr(e.head, (trymacroexpand(a; mod) for a in e.args)...)
end

# ╔═╡ cdc81b89-a0f4-4de4-9b54-f959a757aca4
trymacroexpand(x::Any; mod::Module) = x
```

This works but it's a bit slow

### CODE REVIEW

**Comment by fonsp** [comment]
@Pangoraw What do you think?

**Comment by Pangoraw** [comment]
> This works but it's a bit slow

But we would need to do it in Pluto?

**Comment by fonsp** [comment]
No, I think the slow part is when `macroexpand` fails because the macro is not defined (50ms), but in Pluto's use we only expand macros that are guaranteed to be defined. The way we use EE in Pluto is not changed by this PR because we overload the `explore_macro!` function.

**Comment by fonsp** [comment]
In Pluto we can't just expand known macros, and then call `compute_reactive_node` on the result, because we also do some special handling of Pkg.activate inside the `explore` function:

https://github.com/fonsp/Pluto.jl/blob/2aacc500dd9a947f129f53a2335aba00a5a7ad4a/src/analysis/ExpressionExplorer.jl#L28

**Comment by Pangoraw** [comment]
you are right, I forgot about the special configuration :+1:. I think it makes more sense like this than to expand only a special list such as `@md_str` and such.

**Comment by fonsp** [comment]
But I was wondering if we can turn our special `explore_macro!` code into an expression transformation that we run before `compute_reactive_node`... That way we don't need the AbstractEEConfigration system with overloads anymore. Do you think that's possible, and would that be nicer?

**Comment by Pangoraw** [comment]
Yes, something like that (still needs the MacroHasSpecialHeuristicInside):

```julia
preprocess_expr(other) = other
function preprocess_expr(ex::Expr)
   Meta.isexpr(ex, :macrocall) || return Expr(ex.head, (preprocess_expr(arg) for arg in ex.args)...)

   macro_ = ex.args[1]
   if macro_ in Pluto.ExpressionExplorer.can_macroexpand
       return try
           Expr(:block, macro_, macroexpand(Pluto.PlutoRunner,ex))
       catch
           ex
       end
   end

   ex
end
```
I can open a PR on pluto with this changes to see what it would look like

**Comment by fonsp** [comment]
yes a pr would be nice!

**Comment by fonsp** [comment]
This might work, testing now

```julia
function pretransform_pluto(ex)
    # ExpressionExplorer does not explore inside macro calls, i.e. the arguments of a macrocall (like `a+b` in `@time a+b`) are ignored.
    # Normally, you would macroexpand an expression before giving it to ExpressionExplorer, but in Pluto we sometimes need to explore expressions *before* executing code.
    
    # In those cases, we want most accurate result possible. Our extra needs are:
    # 1. Macros included in Julia base, Markdown and `@bind` can be expanded statically. (See `maybe_macroexpand_pluto`.)
    # 2. If a macrocall argument contains a "special heuristic" like `Pkg.activate()` or `using Something`, we need to surface this to be visible to ExpressionExplorer and Pluto. We do this by placing the macrocall in a block, and copying the argument after to the macrocall.
    # 3. If a macrocall argument contains other macrocalls, we need these nested macrocalls to be visible. We do this by placing the macrocall in a block, and creating new macrocall expressions with the nested macrocall names, but without arguments.
    if Meta.isexpr(ex, :macrocall)
        to_add = Expr[]

        for arg in ex.args[begin+1:end]
            # TODO: test nested macrocalls
            arg_transformed = pretransform_pluto(arg)
            macro_arg_symstate = ExpressionExplorer.compute_symbols_state(arg_transformed)
            
            # When this macro has something special inside like `Pkg.activate()`, we're going to make sure that ExpressionExplorer treats it as normal code, not inside a macrocall. (so these heuristics trigger later)
            if arg isa Expr && macro_has_special_heuristic_inside(symstate = macro_arg_symstate, expr = arg)
                # then the whole argument expression should be added
                # TODO: should we add arg or pretransform_pluto(arg)?
                push!(to_add, arg)
            else
                for fn in macro_arg_symstate.macrocalls
                    push!(to_add, Expr(:macrocall, fn))
                    # fn is a FunctionName
                    # normally this would not be a legal expression, but ExpressionExplorer handles it correctly so it's all cool
                end
            end
        end
        
        Expr(:block, maybe_macroexpand_pluto(ex), to_add...)
    elseif ex isa Expr
        Expr(ex.head, (pretransform_pluto(a) for a in ex.args)...)
    else
        ex
    end
end
```

**Pull request merged**
